### PR TITLE
init server.js & express

### PR DESCRIPTION
**Pull request by jtran6796**

### CODE REVIEW

**Comment by JJCUBER** [comment]
`node_modules` shouldn't be included in commits; you can copy the `.gitignore` I created within the web app subdirectory.

https://github.com/tranpham9/expense-tracker/blob/main/frontend/web/.gitignore

**Comment by JJCUBER** [comment]
To make things simpler (since you have already tracked the node_modules folder), it might be easier to either create a new branch with just server.js, package.json, and package-lock.json **after** creating the .gitignore.  You could also just commit directly to the main branch (so long as you make sure to first commit a .gitignore and double check before committing to make sure the node_modules don't get included) since there aren't any conflicts.

**Comment by jtran6796** [comment]
Would I have to do git rm node_modules? or add the .gitignore in the api or other subdirectory?

**Comment by JJCUBER** [comment]
If you are trying to still use this branch, you would need to first create the .gitignore in the api folder then perform what you mentioned (I believe you would also need the recursive flag, `-r`).  **However**, the node_modules would still be in the history of the repo if this pull request were merged, so I strongly recommend just committing the .gitignore then the 3 files I mentioned prior directly on the main branch.  (That way, the node_modules won't ever be in the history and people won't need to download it every time they clone the repo.)

**Pull request closed without merging**
